### ISSUE TITLE
How to run this model on a single video?

### ISSUE THREAD

**Issue by hopeSerendipity** [vukasin-stanojevic/BoostTrack#1]
I want to make a test of the sota model on my video,could you help me with this because you didn't mention it on the readme.

**Comment by changpowei** [comment]
Same question as @hopeSerendipity! How to test the algorithm on my own video? Thx

**Comment by vukasin-stanojevic** [comment]
Hello, 
Check the lines 159-171 from main.py: 
`
pred = det(img, tag)
start_time = time.time()

if pred is None:
    continue

targets = tracker.update(pred, img, np_img[0].numpy(), tag)
tlwhs, ids, confs = utils.filter_targets(targets, args.aspect_ratio_thresh, args.min_box_area)

total_time += time.time() - start_time
frame_count += 1

results[video_name].append((frame_id, tlwhs, ids, confs))
`
The lines 159, 165, and 166 are particularly important. 
To run on your video you would have to pass the frame (img variable) of your video in line 159 and after the line 166 add some visualisation (in my tests I used cv2 library, cv2.rectangle(...)). All the data you need is in tlshs and ids. 

In case you want to test the post-processed results you could just run the algorithm once and then use generated results from <experiment_name>_post_gbi folder to draw the bounding boxes, IDs, etc...

Generated txt files are formatted by instructions from the [MOT Challenge website](https://motchallenge.net/instructions/). 
`<frame>, <id>, <bb_left>, <bb_top>, <bb_width>, <bb_height>, <conf>, <x>, <y>, <z>` 

I Hope this helps!

@changpowei @hopeSerendipity

**Comment by vukasin-stanojevic** [comment]
@alaap001, there should be no problem with the detector. You probably "confused" it somehow by specifying same paths for different videos. Anyway, if there is any problem with the detector cache, you could simply clear the cache folder and comment the lines 176-177 from main.py to forbid further caching of the results.

**Comment by alaap001** [comment]
```
An error occurred: ERROR: The number of cached embeddings don't match the number of detections.
Was the detector model changed? Delete cache if so.
Traceback (most recent call last):
  File "/media/alaap/PF_bkp1/videos/tracking testing/BoostTrack/boosttracktest.py", line 182, in <module>
    targets = tracker.update(filtered_dets, im, im, '')
  File "/media/alaap/PF_bkp1/videos/tracking testing/BoostTrack/tracker/boost_track.py", line 227, in update
    dets_embs = self.embedder.compute_embedding(img_numpy, dets[:, :4], tag)
  File "/media/alaap/PF_bkp1/videos/tracking testing/BoostTrack/tracker/embedding.py", line 108, in compute_embedding
    raise RuntimeError(
RuntimeError: ERROR: The number of cached embeddings don't match the number of detections.
Was the detector model changed? Delete cache if so.
```

this is an error from compute embedding, can you please tell what the cause of this error could be?

**Comment by alaap001** [comment]
I got it to work, I by mistake sent numpy image instead of tensor.

**Comment by mrigankEvig** [comment]
> I got it to work, I by mistake sent numpy image instead of tensor.

hi can you please share how you got it to work on yolov10...

**Comment by TheMattBin** [comment]
@alaap001 @vukasin-stanojevic  may I know that how you get the image_tensor as i think it would be helpful for me to cook up my own inference code? Thanks!
