### ISSUE TITLE
Can I run the model on the custom dataset?

### ISSUE THREAD

**Issue by jaehongk** [vukasin-stanojevic/BoostTrack#13]
Hello Vukasin,

Thank you for this excellent open source project.
I wish to run inference on my own dataset using the provided weight. Is there a function to load and infer any custom dataset? Thank you for your time!

**Comment by vukasin-stanojevic** [comment]
Hello @jaehongk , 
In case you already have a trained YOLOX-X model, it is very simple. You need to make only few changes.

1. Add a branch after line 44 in main.py.
2. Modify function get_detector_path_and_im_size() (it is called from main.py in line 65).
3. Modify function get_mot_loader() from dataset.py folder.

Note 1: all these modifications are simply adding if/elif branches and setting the right path and/or dataset name.
Note 2: after modifying the functions I mentioned, you will be able to switch between different datasets by simply specifying dataset argument in command line. 

Best regards!
Vukašin

**Comment by jaehongk** [comment]
Thank you so much for your kind response!

Sincerely,
Jaehong
