### ISSUE TITLE
Reproduce paper result

### ISSUE THREAD

**Issue by trongldwork** [vukasin-stanojevic/BoostTrack#6]
I clone your repo and do setting like instruction, but i cant reproduce the result in your paper, with --no_reid and full method you provide in paper, my result is 
![image](https://github.com/user-attachments/assets/0684be41-9825-4364-a37f-8bcff5e3349e)

**Comment by vukasin-stanojevic** [comment]
Hello. The original results from the paper are obtained on the machine with very unusual python - conda setup. There was a lot of dependency conflicts which I somehow managed to resolve. The result was that somehow it used some packages from the base interpreter and some from the conda environment. 

After submitting the paper, I tried to setup repository from the start and manage to do it with different package versions (resulting in the simple setup described in the readme file). 
The results obtained with this new version are slightly different (usually the difference is only on the second decimal and "unbiased" - better for some metrics and worse for the other). 

Based on the numbers you present, I assume you tried it on MOT20. 
Below I list the results from the paper:

MOT17 validation set:
| Method      | HOTA   |  MOTA  |  IDF1  |  IDSW  |
|-------------|--------|--------|--------|--------|
| BoostTrack  |  71.63   |  80.692  |  83.959  | 97 |
| BoostTrack+ |  72.411  |  80.67  |  85.385  | 81 |

MOT20 validation set:
| Method      | HOTA   |  MOTA  |  IDF1  |  IDSW  |
|-------------|--------|--------|--------|--------|
|BoostTrack   | 61.846   | 77.442 | 77.584 | 882 |
|BoostTrack+  | 62.68 | 77.731 | 79.088 | 781 |

The results I get with different package versions:

MOT17 validation set:
| Method      | HOTA   |  MOTA  |  IDF1  |  IDSW  |
|-------------|--------|--------|--------|--------|
| BoostTrack  |  71.532   |  80.7  |  83.875  | 104 |
| BoostTrack+ |  72.407  |  80.941  |  85.091  | 83 |

MOT20 validation set:
| Method      | HOTA   |  MOTA  |  IDF1  |  IDSW  |
|-------------|--------|--------|--------|--------|
|BoostTrack   | 61.742   | 77.464 | 77.454 | 898 |
|BoostTrack+  |  62.691  |  77.717 | 79.081  | 787 |

The small differences in base results probably increase with applying the post-processing. However, the overall results are not too much different. Sorry for the inconvenience. You can consider the results you get as "normal".

Stay tuned for the new method that's build upon BoostTrack. It is implemented and tested with stable package versions :)

**Comment by yhl2018** [comment]
Hello, could you please provide the results for the test set? My reproduction of the results submitted is very poor compared to the val set and yours.
