### ISSUE TITLE
Can it be trained on a custom dataset?

### ISSUE THREAD

**Issue by Stangerine** [vukasin-stanojevic/BoostTrack#9]

**Comment by vukasin-stanojevic** [comment]
Hello, 
We use YOLOX-X model trained by ByteTrack as detector module. The focus of our papers is not on improving detector performance, but to try to do as much as possible with imperfect detector. 

You can use any other detector or change weights of the YOLOX-X (retrain it or fine-tune it). The only important thing is that the tracker object receives detected bounding boxes and the image.
Please check the [response ](https://github.com/vukasin-stanojevic/BoostTrack/issues/7#issuecomment-2274410601) to a similar question. 

If you are interested in ReID, we use weights from Deep OC-SORT.

The components used in BoostTrack (similarity and detection boosts) are not trainable (except for Kalman filter which works online), but we used the same setting in MOT17 and MOT20 hopping not to overfit the values.
